import './themes/default/var.less'
import './themes/light/var.less'
import './themes/dark/var.less'
import 'virtual:uno.css'
import '@unocss/reset/tailwind.css'
import '@unocss/reset/tailwind-compat.css'
import 'nprogress/nprogress.css'
import 'animate.css'
import './main.less'
// import 'virtual:svg-icons-register'
// import 'virtual:unocss-devtools'
